export const STORY_TAG_OPTIONS = [
  "Hành Động",
  "Phiêu Lưu",
  "Hài Hước",
  "Chính Kịch",
  "Giả Tưởng",
  "Lãng Mạn",
  "Isekai (Chuyển Sinh)",
  "Kinh Dị",
  "Bí Ẩn",
  "Đời Thường",
  "Học Đường",
  "Siêu Nhiên",
  "Tâm Lý",
  "Khoa Học Viễn Tưởng",
  "Bi Kịch",
  "Võ Thuật",
  "Lịch Sử",
  "Thể Thao",
  "Manhwa",
  "Manhua",
  "Webtoon",
  "Josei",
  "Seinen",
  "Shounen",
  "Shoujo",
] as const;